<a href="https://colab.research.google.com/github/rkgupta7463/ML-projects-code/blob/main/phone_recommendation_systems(updated).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### How to use this project to in your colab notebook
**Follow the steps:-**
1. Download Your Kaggle APIs Key and password file from your kaggle account in setting section

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mobile-recommendation-system-dataset/mobile_recommendation_system_dataset.csv


In [ ]:
df=pd.read_csv('/kaggle/input/mobile-recommendation-system-dataset/mobile_recommendation_system_dataset.csv')

In [ ]:
df.shape

(2546, 5)

In [ ]:
df.head()

name  ratings    price  \
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2    23999   
1        OPPO F11 Pro (Aurora Green, 128 GB)      4.5  ₹20,999   
2     REDMI Note 11 (Starburst White, 64 GB)      4.2    13149   
3     OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1    21999   
4        APPLE iPhone 13 mini (Blue, 128 GB)      4.6     3537   

                                              imgURL  \
0  https://rukminim2.flixcart.com/image/312/312/x...   
1  https://rukminim2.flixcart.com/image/312/312/k...   
2  https://rukminim2.flixcart.com/image/312/312/x...   
3  https://rukminim2.flixcart.com/image/312/312/x...   
4  https://rukminim2.flixcart.com/image/312/312/k...   

                                              corpus  
0  Storage128 GBRAM6  SystemAndroid 12Processor T...  
1  Storage128 GBRAM6 GBExpandable Storage256GB  S...  
2  Storage64 GBRAM4  SystemAndroid 11Processor Sp...  
3  Storage256 GBRAM12  SystemAndroid Q 11Processo...  
4  Storage128  SystemiOS 15Processor TypeA15 Bion...

In [ ]:
df.tail()

name  ratings  price  \
2541                 REDMI Note 9 (Shadow Black, 64 GB)      4.3  11999   
2542                OnePlus 9 5G (Astral Black, 128 GB)      3.9  30203   
2543                                       Motorola a50      4.1   1549   
2544  SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...      4.3  20463   
2545                  vivo T2x 5G (Aurora Gold, 128 GB)      4.4  13999   

                                                 imgURL  \
2541  https://rukminim2.flixcart.com/image/312/312/k...   
2542  https://rukminim2.flixcart.com/image/312/312/x...   
2543  https://rukminim2.flixcart.com/image/312/312/k...   
2544  https://rukminim2.flixcart.com/image/312/312/x...   
2545  https://rukminim2.flixcart.com/image/312/312/x...   

                                                 corpus  
2541  Storage64 GBRAM4 GBExpandable Storage512GB  Sy...  
2542  Storage128 GBRAM8  SystemAndroid 11Processor S...  
2543                                                NaN  
2544  Storage256 GBRAM12  SystemAndroid 12Processor ...  
2545  Storage128 GBRAM6  SystemAndroid 13Processor T...

In [ ]:
df['corpus'].iloc[1]

'Storage128 GBRAM6 GBExpandable Storage256GB  SystemAndroid Pie 9.0Processor TypeMediaTek Helio P70 Octa Core 2.1 GHzProcessor Speed2.1 48MP 5MP 48MP 5MP 48MP 5MP 48MP 5MP 48MP 5MP 16MP 3G Capacity4000 Display Size16.51 cm (6.5 inch)Resolution2340 x 1080 pixelsResolution TypeFull HD+GPUARM Mali-G72 MP3 at 900 MHzDisplay Colors16MOther Display FeaturesScreen Texture: TFT-LTPS, In-cell Touch Panel Technology, Narrow Frame: 1.70mm (Size from AA to Outside Edge of Glass), Screen Ratio: 90.90%, Screen Contrast: 1500:1 (Typical), Color Saturation: NTSC 81.5% (Typical), Maximum Brightness: 480 nits (Typical), Touch Screen Supplier: DSBJ, TM, Touch Panel Glass Type: Dragontrail'

In [ ]:
print(df['imgURL'].iloc[1])
print(df['name'].iloc[1])

https://rukminim2.flixcart.com/image/312/312/k01b8280pkrrdj/mobile-refurbished/8/w/n/f11-pro-128-d-cph1969-oppo-6-original-imafec8hzfzyg79e.jpeg?q=70
OPPO F11 Pro (Aurora Green, 128 GB)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2546 entries, 0 to 2545
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     2546 non-null   object 
 1   ratings  2546 non-null   float64
 2   price    2546 non-null   object 
 3   imgURL   2546 non-null   object 
 4   corpus   2534 non-null   object 
dtypes: float64(1), object(4)
memory usage: 99.6+ KB


In [ ]:
df['price'].iloc[:10]

0      23999
1    ₹20,999
2      13149
3      21999
4       3537
5       5537
6      18996
7       9999
8      16999
9      12999
Name: price, dtype: object

In [ ]:
df['price']=df['price'].str.replace('₹','')

In [ ]:
df['price']=df['price'].str.replace(',','').astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2546 entries, 0 to 2545
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     2546 non-null   object 
 1   ratings  2546 non-null   float64
 2   price    2546 non-null   int64  
 3   imgURL   2546 non-null   object 
 4   corpus   2534 non-null   object 
dtypes: float64(1), int64(1), object(3)
memory usage: 99.6+ KB


In [ ]:
df.isnull().sum()

name        0
ratings     0
price       0
imgURL      0
corpus     12
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

name       0
ratings    0
price      0
imgURL     0
corpus     0
dtype: int64

In [ ]:
df.shape

(2534, 5)

In [ ]:
df.head()

name  ratings  price  \
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2  23999   
1        OPPO F11 Pro (Aurora Green, 128 GB)      4.5  20999   
2     REDMI Note 11 (Starburst White, 64 GB)      4.2  13149   
3     OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1  21999   
4        APPLE iPhone 13 mini (Blue, 128 GB)      4.6   3537   

                                              imgURL  \
0  https://rukminim2.flixcart.com/image/312/312/x...   
1  https://rukminim2.flixcart.com/image/312/312/k...   
2  https://rukminim2.flixcart.com/image/312/312/x...   
3  https://rukminim2.flixcart.com/image/312/312/x...   
4  https://rukminim2.flixcart.com/image/312/312/k...   

                                              corpus  
0  Storage128 GBRAM6  SystemAndroid 12Processor T...  
1  Storage128 GBRAM6 GBExpandable Storage256GB  S...  
2  Storage64 GBRAM4  SystemAndroid 11Processor Sp...  
3  Storage256 GBRAM12  SystemAndroid Q 11Processo...  
4  Storage128  SystemiOS 15Processor TypeA15 Bion...

In [ ]:
df['corpus'].iloc[1]

'Storage128 GBRAM6 GBExpandable Storage256GB  SystemAndroid Pie 9.0Processor TypeMediaTek Helio P70 Octa Core 2.1 GHzProcessor Speed2.1 48MP 5MP 48MP 5MP 48MP 5MP 48MP 5MP 48MP 5MP 16MP 3G Capacity4000 Display Size16.51 cm (6.5 inch)Resolution2340 x 1080 pixelsResolution TypeFull HD+GPUARM Mali-G72 MP3 at 900 MHzDisplay Colors16MOther Display FeaturesScreen Texture: TFT-LTPS, In-cell Touch Panel Technology, Narrow Frame: 1.70mm (Size from AA to Outside Edge of Glass), Screen Ratio: 90.90%, Screen Contrast: 1500:1 (Typical), Color Saturation: NTSC 81.5% (Typical), Maximum Brightness: 480 nits (Typical), Touch Screen Supplier: DSBJ, TM, Touch Panel Glass Type: Dragontrail'

In [ ]:
import nltk

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
def TextStem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [ ]:
TextStem(df['corpus'].iloc[0])

'storage128 gbram6 systemandroid 12processor typemediatek dimens 1080processor speed2.6 50mp 8mp 2mp 50mp 16mp 5G capacity5000 display size16.94 cm (6.67 inch)resolution2400 x 1080 pixelsresolut typeful hd+ amol displaygpuarm mali-g68 mc4display typeful hd+ amol displayoth display featuresrefresh rate: 120 hz, contrast: 5,000,000:1, 1920hz pwm dimming, bright level: 16000:1, peak brightness: 900 nit'

In [ ]:
df['corpus']=df['corpus'].apply(TextStem)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_features=500,stop_words='english')

In [ ]:
vector=cv.fit_transform(df['corpus']).toarray()

In [ ]:
vector

array([[0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
cv.get_feature_names_out()

array(['00', '000', '02', '05', '07', '09', '0processor', '10', '100',
       '1000', '100000', '1000000', '1080', '108mp', '10mp',
       '10processor', '11', '1170', '11processor', '12', '120', '1200',
       '120hz', '1284', '12mp', '12processor', '13', '1300', '13mp',
       '13processor', '14', '1400', '1440', '14processor', '1500',
       '15processor', '16', '1600', '16mp', '16processor', '180', '180hz',
       '1processor', '20', '200', '2000000', '20mp', '21', '22', '2340',
       '2400', '2408', '240hz', '25mp', '26', '27', '2d', '2g', '2mp',
       '2processor', '2x', '32', '32mp', '33', '36', '360', '3d', '3g',
       '3mp', '400', '400nit', '41', '43', '430', '44', '44mp', '450',
       '48', '480', '48mp', '49', '4g', '50', '500', '5000000', '500nit',
       '506display', '50mp', '51', '52', '53', '54', '55', '56', '58',
       '59', '5d', '5g', '5gprocessor', '5mp', '60', '600', '60hz',
       '610display', '619display', '625', '63mp', '64', '642ldisplay',
       '64mp',

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vector)

In [ ]:
similarity

array([[1.        , 0.25770721, 0.37890539, ..., 0.34732994, 0.25776089,
        0.63344515],
       [0.25770721, 1.        , 0.16003201, ..., 0.28005602, 0.09331389,
        0.23105534],
       [0.37890539, 0.16003201, 1.        , ..., 0.58823529, 0.2057983 ,
        0.42911912],
       ...,
       [0.34732994, 0.28005602, 0.58823529, ..., 1.        , 0.2057983 ,
        0.3933592 ],
       [0.25776089, 0.09331389, 0.2057983 , ..., 0.2057983 , 1.        ,
        0.2502173 ],
       [0.63344515, 0.23105534, 0.42911912, ..., 0.3933592 , 0.2502173 ,
        1.        ]])

In [ ]:
similarity[1]

array([0.25770721, 1.        , 0.16003201, ..., 0.28005602, 0.09331389,
       0.23105534])

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:11]

[(68, 1.0000000000000002),
 (303, 1.0000000000000002),
 (616, 0.9830508474576274),
 (1461, 0.9830508474576274),
 (457, 0.9661016949152545),
 (1027, 0.9661016949152545),
 (1735, 0.9661016949152545),
 (569, 0.9479521354771159),
 (1123, 0.9479521354771159),
 (1540, 0.9479521354771159)]

In [ ]:
def recommend_descriptions(phone):
    phone_index = df[df['name'] == phone].index
    if len(phone_index) == 0:
        print("Phone not found in the dataset.")
        return []

    phone_index = phone_index[0]
    distances = similarity[phone_index]
    phoneLists = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:16]

    recommended_phones = []
    for i in phoneLists:
        recommended_phone_name = new_df.iloc[i[0]]['name']
        recommended_phones.append(recommended_phone_name)

    return recommended_phones

In [ ]:
phone_name=input("Enter the phone name")

Enter the phone name REDMI Note 11 (Starburst White, 64 GB)


In [ ]:
recommend_descriptions(phone_name)#].loc[:1]

['REDMI Note 11 (Horizon Blue, 64 GB)',
 'REDMI Note 11 (Space Black, 64 GB)',
 'REDMI Note 11 (Starburst White, 64 GB)',
 'REDMI Note 11 (Space Black, 64 GB)',
 'REDMI Note 11 (Horizon Blue, 128 GB)',
 'REDMI Note 11S (Horizon Blue, 64 GB)',
 'REDMI Note 11S (Space Black, 64 GB)',
 'REDMI Note 11 (Starburst White, 128 GB)',
 'SAMSUNG Galaxy M32 (Black, 64 GB)',
 'Redmi 10 Prime (Phantom Black, 64 GB)',
 'REDMI Note 10 lite (Glacier White, 64 GB)',
 'REDMI Note 11T 5G (Aquamarine Blue, 64 GB)',
 'Redmi 10 Prime (Phantom Black, 64 GB)',
 'Redmi 10 Prime (Bifrost Blue, 64 GB)',
 'Redmi 10 Prime (Astral White, 64 GB)']

In [ ]:
def recommend_descriptions_photos(phone):
    phone_index = df[df['name'] == phone].index
    if len(phone_index) == 0:
        print("Phone not found in the dataset.")
        return []

    phone_index = phone_index[0]
    distances = similarity[phone_index]
    phoneLists = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:10]

    recommended_phones = []
    for i in phoneLists:
        recommended_phone_name = new_df.iloc[i[0]]['name']
        recommended_phone_imgurl = df.iloc[i[0]]['imgURL']
        recommended_phones.append((recommended_phone_name, recommended_phone_imgurl))

    return recommended_phones

In [ ]:
recommend_descriptions_photos('OPPO F11 Pro (Aurora Green, 128 GB)')

[('OPPO F11 Pro (Thunder Black, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k01b8280pkrrdj/mobile/d/g/s/oppo-f11-pro-cph1969-original-imafec8h3uqk3fqw.jpeg?q=70'),
 ('OPPO F11 Pro (Thunder Black, 64 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k01b8280pkrrdj/mobile/d/g/s/oppo-f11-pro-cph1969-original-imafec8h3uqk3fqw.jpeg?q=70'),
 ('OPPO F11 Pro (Waterfall Grey, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k73nlow0/mobile/g/5/2/oppo-f11-pro-cph1969-original-imafpfybdkcp5yqt.jpeg?q=70'),
 ('OPPO F11 (Fluorite Purple, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/m/p/6/f11-128-c-cph1911-oppo-4-original-imafght4bbcxzmgc.jpeg?q=70'),
 ('OPPO F11 (Marble Green, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/z/a/f/f11-128-a-cph1911-oppo-4-original-imafght4kvkhnzzg.jpeg?q=70'),
 ('OPPO F11 (Jewelry White, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jby

In [ ]:
import pickle as pkl

In [ ]:
with open('Similarity_Matrix_1.pkl', 'wb') as file:
    pkl.dump(similarity, file)

In [ ]:
similar=pkl.load(open("Similarity_Matrix_1.pkl","rb"))

**Implemented with Similar Name of Phone and their descriptions**

In [ ]:
main_df = pd.Series(df['name'] + " " + df['corpus'], name="descriptions")

In [ ]:
main_df=pd.DataFrame(main_df)

In [ ]:
new_df1=df.copy()

In [ ]:
print(new_df1.columns)
print(main_df.columns)

Index(['name', 'ratings', 'price', 'imgURL', 'corpus'], dtype='object')
Index(['descriptions'], dtype='object')


In [ ]:
final=pd.concat([new_df1, main_df], axis=1)

In [ ]:
final_df=final.drop(columns='corpus')

In [ ]:
final_df.head()

name  ratings  price  \
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2  23999   
1        OPPO F11 Pro (Aurora Green, 128 GB)      4.5  20999   
2     REDMI Note 11 (Starburst White, 64 GB)      4.2  13149   
3     OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1  21999   
4        APPLE iPhone 13 mini (Blue, 128 GB)      4.6   3537   

                                              imgURL  \
0  https://rukminim2.flixcart.com/image/312/312/x...   
1  https://rukminim2.flixcart.com/image/312/312/k...   
2  https://rukminim2.flixcart.com/image/312/312/x...   
3  https://rukminim2.flixcart.com/image/312/312/x...   
4  https://rukminim2.flixcart.com/image/312/312/k...   

                                        descriptions  
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB) stor...  
1  OPPO F11 Pro (Aurora Green, 128 GB) storage128...  
2  REDMI Note 11 (Starburst White, 64 GB) storage...  
3  OnePlus Nord CE 5G (Blue Void, 256 GB) storage...  
4  APPLE iPhone 13 mini (Blue, 128 GB) storage128...

In [ ]:
vector2=cv.fit_transform(final_df['descriptions']).toarray()

In [ ]:
vector2

array([[0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
similarity2=cosine_similarity(vector2)

In [ ]:
similarity2[1]

array([0.26628462, 1.        , 0.1537395 , ..., 0.26756002, 0.09598942,
       0.23411502])

In [ ]:
def recommend_similiar_phone_name_with_des(phone):
    phone_index = df[df['name'] == phone].index
    if len(phone_index) == 0:
        print("Phone not found in the dataset.")
        return []

    phone_index = phone_index[0]
    distances = similarity2[phone_index]
    phoneLists = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:10]

    recommended_phones = []
    for i in phoneLists:
        recommended_phone_name = df.iloc[i[0]]['name']
        recommended_phone_imgurl = df.iloc[i[0]]['imgURL']
        recommended_phones.append((recommended_phone_name, recommended_phone_imgurl))

    return recommended_phones

In [ ]:
recommend_similiar_phone_name_with_des('OPPO F11 Pro (Aurora Green, 128 GB)')

[('OPPO F11 Pro (Thunder Black, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k01b8280pkrrdj/mobile/d/g/s/oppo-f11-pro-cph1969-original-imafec8h3uqk3fqw.jpeg?q=70'),
 ('OPPO F11 Pro (Waterfall Grey, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k73nlow0/mobile/g/5/2/oppo-f11-pro-cph1969-original-imafpfybdkcp5yqt.jpeg?q=70'),
 ('OPPO F11 Pro (Thunder Black, 64 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k01b8280pkrrdj/mobile/d/g/s/oppo-f11-pro-cph1969-original-imafec8h3uqk3fqw.jpeg?q=70'),
 ('OPPO F11 (Marble Green, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/z/a/f/f11-128-a-cph1911-oppo-4-original-imafght4kvkhnzzg.jpeg?q=70'),
 ('OPPO F11 (Marble Green, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/n/y/p/f11-128-a-cph1911-oppo-6-original-imafg4zzjz8mjjwr.jpeg?q=70'),
 ('OPPO F11 (Fluorite Purple, 128 GB)',
  'https://rukminim2.flixcart.com/image/312/312/k2jbyq

In [ ]:
with open('Similarity_Matrix_2.pkl', 'wb') as file:
    pkl.dump(similarity2, file)

In [ ]:
similar2=pkl.load(open("Similarity_Matrix_1.pkl","rb"))